// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/BackTop/BackTop.vue')['default']
    Button: typeof import('vue-devui')['default']
    Content: typeof import('vue-devui')['default']
    DContent: typeof import('vue-devui/content/index.es.js')['Content']
    DFooter: typeof import('vue-devui/footer/index.es.js')['Footer']
    DLayout: typeof import('vue-devui/layout/index.es.js')['Layout']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElMain: typeof import('element-plus/es')['ElMain']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Fullscreen: typeof import('vue-devui')['default']
    FullScreen: typeof import('./src/components/FullScreen/FullScreen.vue')['default']
    FullScreenTauri: typeof import('./src/components/FullScreen/FullScreenTauri.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconHeroiconsOutlineArrowsExpand: typeof import('~icons/heroicons-outline/arrows-expand')['default']
    'IconIconParkOutline:fullScreenPlay': typeof import('~icons/icon-park-outline/full-screen-play')['default']
    IconIconParkOutlineFullScreenPlay: typeof import('~icons/icon-park-outline/full-screen-play')['default']
    IHeroiconsOutlineArrowsExpand: typeof import('~icons/heroicons-outline/arrows-expand')['default']
    Layout: typeof import('vue-devui')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TauriVer: typeof import('./src/components/Tauri/TauriVer.vue')['default']
    VarBackTop: typeof import('@varlet/ui')['_BackTopComponent']
  }
}
